#!/bin/bash

#Dans ce script, on va utiliser le principe de HASH MD5 pour definir la version d'un fichier.
#Si un hash md5 ne correspond pas a nos attente, sa veux dire que le fichier a ete modifier. donc mis a jour !
#Grace a cela, on va pouvoir definir si le fichier crontab a ete update!

#Premiere chose, on garde en memoire le sum de crontab . 
MD5SUM='cat /root/crontabsum'

#En suite, on genere un nouveau SUM de la crontab 
NEWSUM='md5sum /etc/crontab | cut -d " " -f 1'

#Si le nouveau SUM n'est pas identique, alors on a modifier le fichier crontab.
if [ "$MD5SUM" != "$NEWSUM" ]
then
    #ON met a jour le hash MD5 du fichier pour bien garder notre fichier udpate
	md5sum /etc/crontab | cut -d " " -f 1 > /root/crontabsum
    #On envois un email au root pour dire que le fichier sum a ete Update
	mail -s "The file crontab was modified" root@localhost.com < /etc/crontab
fi


#Pour deployer ce script, on va definir une tache CRON
#0 0 * * *   root    sh /root/<nom_du_script>

#toujours, check Crontab Guru